### ISSUE TITLE
master broken on 5.4.3: TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by stromnet** [flant/grafana-statusmap#100]
Attempted to use this plugin with Grafana 5.4.3 (unfortunately latest on FreeBSD). Checked out the git repo into plugins dir and attempted to use. 
Master has the following problems, checking out 0.2.0 tag works fine though, so probably a regression?

Looking in the webkit inspector, "undefined" value here might refer to the datasource variable, but not sure.. 
A datasource was selected though.

```
TypeError: Cannot read property 'query' of undefined
    at StatusHeatmapCtrl.e.issueQueries (https://example.com/grafana/public/build/app.469095018b321ef1da7c.js:22:485696)
    at StatusHeatmapCtrl.issueQueriesWithInterval (https://example.com/grafana/public/plugins/flant-statusmap-panel/module.js:506:96)
    at eval (https://example.com/grafana/public/plugins/flant-statusmap-panel/module.js:491:31)
    at https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:92198
    at https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:92295
    at l.$digest (https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:97589)
    at https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:99404
    at h (https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:33038)
    at https://example.com/grafana/public/build/vendor.469095018b321ef1da7c.js:130:34396
```

**Comment by diafour** [comment]
Hello! Which version of FreeBSD do you use? I see grafana6 port on pkgs.org.

**Comment by stromnet** [comment]
Ah, nice! I've missed that, my bad. Thanks for the tip, will upgrade!

Still, README.md in master claims 5.4.3, so if it is intended to still work there, should probably be looked into.

**Comment by diafour** [comment]
Thank you! The problem was with recently implemented workaround. Fixed.

**Comment by stromnet** [comment]
Pulled & verified, now works as expected! Thanks for quick fix!
