### ISSUE TITLE
Object doesn't support property or method 'remove'

### ISSUE THREAD

**Issue by shep89** [flant/grafana-statusmap#40]
Getting this error in IE 11. 
Same graph 
IE 11:
![default](https://user-images.githubusercontent.com/12829965/51161560-f2938200-18a3-11e9-9060-07aab821aa40.png)
Chrome:
![default](https://user-images.githubusercontent.com/12829965/51161601-15259b00-18a4-11e9-9877-24a9eac82557.png)

TypeError: Object doesn't support property or method 'remove'
   at Anonymous function (eval code:90:7)
   at nt.prototype.each (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:35:151122)
   at drawDiscreteColorLegend (eval code:85:5)
   at render (eval code:403:19)
   at Anonymous function (eval code:384:15)
   at s.prototype.emit (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:86:11785)
   at t.prototype.emit (http://stats.afm.renault.ru/public/build/app.469095018b321ef1da7c.js:1:181430)
   at t.prototype.render (http://stats.afm.renault.ru/public/build/app.469095018b321ef1da7c.js:22:477825)
   at _this.onDataReceived (eval code:176:13)
   at s.prototype.emit (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:86:11348)

**Comment by dennisdahlmann** [comment]
Same error applies in our environment: Grafana 5.2.4 with Statusmap panel 0.0.4.
It is working with Firefox 65 and 71.0.3578.98, but not with IE 11

**Comment by diafour** [comment]
It looks that `.remove()` is not supported in IE but there is a workaround with `removeChild()`. Will be fixed in next release.
