### ISSUE TITLE
Unable to get property 'removeChild' of undefined or null reference

### ISSUE THREAD

**Issue by shep89** [flant/grafana-statusmap#49]
Just updated after this issue https://github.com/flant/grafana-statusmap/issues/40, PR https://github.com/flant/grafana-statusmap/pull/48

Error actual only for IE 11.
TypeError: Unable to get property 'removeChild' of undefined or null reference
   at Anonymous function (eval code:90:7)
   at nt.prototype.each (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:35:151122)
   at drawDiscreteColorLegend (eval code:85:5)
   at render (eval code:403:19)
   at Anonymous function (eval code:384:15)
   at s.prototype.emit (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:86:11785)
   at t.prototype.emit (http://stats.afm.renault.ru/public/build/app.469095018b321ef1da7c.js:1:181430)
   at t.prototype.render (http://stats.afm.renault.ru/public/build/app.469095018b321ef1da7c.js:22:477825)
   at _this.onDataReceived (eval code:176:13)
   at s.prototype.emit (http://stats.afm.renault.ru/public/build/vendor.469095018b321ef1da7c.js:86:11348)

![default](https://user-images.githubusercontent.com/12829965/53387186-afdec280-3996-11e9-8143-71eeb74b89e4.png)

**Comment by diafour** [comment]
It seems that d3 `remove` method is now working in IE11.

But legend only works for discrete mode and not for opacity/spectrum. Sorry, I don't have more time to debug legend in IE11.

**Comment by diafour** [comment]
@shep89 is this still reproducible in IE11?

**Comment by shep89** [comment]
Oh, now its working!
Chrome
![image](https://user-images.githubusercontent.com/12829965/53858904-f19de780-3fec-11e9-8d56-6f0f46ff64b4.png)
IE
![image](https://user-images.githubusercontent.com/12829965/53858911-fa8eb900-3fec-11e9-9c4c-9746ec9ae2d5.png)
